language: objective-c
before:
  - bundle
  - cd Example/HeapInspectorExample && bundle exec pod install
xcode_project: Example/HeapInspectorExample/HeapInspectorExample.xcworkspace
xcode_scheme: HeapInspectorExample

